---
- hosts: geek
  become: yes
  vars_files:
    - vars/wordpress.yml
  pre_tasks:
    - name: Set discovered Ansible Python interpreter.
      set_fact:
        ansible_python_interpreter: "{{ ansible_facts.python.executable }}"
      when: ansible_python_interpreter is not defined
  roles:
    - { role: geerlingguy.nginx, tags: [nginx] }
    - { role: geerlingguy.php, tags: [php] }
    - { role: geerlingguy.mysql, tags: [mysql] }
    - { role: wordpress, tags: [wordpress, app] }
  post_tasks:
    - name: check all
      debug: